# Generated by Django 2.0.5 on 2018-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(verbose_name='內容')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
