# Generated by Django 2.0.5 on 2018-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30, verbose_name='項目')),
                ('kind', models.IntegerField(choices=[(1, '飲食'), (2, '衣服'), (3, '交通'), (4, '教育'), (5, '娛樂'), (6, '其它')], default=0, verbose_name='類別')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
